import time
numeros = list(range(11))
print(f'=' * 24)
print(numeros)
print(f'=' * 24)
time.sleep(2)
print(f'=' * 24)
print('Ordem decrescente...')
print(f'=' * 24)
print('Preparando ordem decrescente...')
print(f'=' * 24)
time.sleep(2)
print('Ordem descrescente preparada')
print(f'=' * 24)
print('rodando...')
print(f'=' * 24)
numbers = list(range(20, -1, -1))
print(numbers)
time.sleep(1.5)
print(f'=' * 24)
print('Ordem realizada com sucesso!')
print(f'=' * 24)